[package]
authors = ["seasnail1"]
repository = "https://github.com/user93390/Lunara"
license = "Apache-2.0"
version = "1.0.0"
name = "Lunara"
edition = "2021"
rust-version = "1.92.0"

[dependencies]
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.15", features = ["with-uuid-1"] }
axum = { version = "0.8.8", features = ["macros"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
dotenv = "0.15.0"
log = "0.4.29"
color-eyre = "0.6.5"
env_logger = "0.11.8"