services:
  postgres_database:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_dat:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  application:
    image: lunara
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - postgres_database

volumes:
  postgres_dat: