services:
  postgres_database:
    image: postgres:alpine3.20
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - postgres_dat:/var/lib/postgresql/data

  application:
    image: lunara
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres_database
    security_opt:
      - seccomp:unconfined

volumes:
  postgres_dat: