services:
  postgres_database:
    image: postgres:alpine3.20
    ports:
      - "5433:5432"
    volumes:
      - postgres_dat:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  application:
    image: lunara
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres_database
    volumes:
      - keyring_service:/root/.local/share/keyrings

volumes:
  postgres_dat:
  keyring_service: