# General
hard_tabs = false
tab_spaces = 4
max_width = 120
use_small_heuristics = "Default"
newline_style = "Auto"
brace_style = "SameLineWhere"
fn_args_density = "Wide"
fn_call_width = 90
merge_derives = false
format_strings = true

# Imports
merge_imports = true
imports_layout = "Horizontal"
reorder_imports = true
imports_indent = "Block"
imports_granularity = "One"
group_imports = "StdExternalCrate"