comment_width = 100
format_code_in_doc_comments = true
fn_params_layout = "Compressed"
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
reorder_imports = true
newline_style = "Unix"
indent_style = "Block"
brace_style = "PreferSameLine"
color = "Always"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 20
force_multiline_blocks = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
